project:
  type: website
  output-dir: docs
  
website:
  title: "EMU660 Assignment 1 - Emre Can Serin"
  site-url: https://emreserincan-design.github.io/emu660-assignment1-emrecanserin/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: assignments/assignment-1.qmd
        text: Assignment 1

format:
  html:
    theme: cosmo
    toc: true